### PR TITLE
Moved command option `--output -` to end of argument list

### PR DESCRIPTION
**Pull request by petemoore**
Let's see if this affects test results...

### CODE REVIEW

**Comment by petemoore** [comment]
Git bisect tells me this problem got added in https://github.com/urfave/cli/commit/3a87b13b01ac8628694f1e1b20bdb452cc0f54d2 from PR urfave/cli#712. Unfortunately this has broken our library.

Options are:
1) vendoring to an older revision
2) using a different command line parsing library
3) making it clear that command options need to be specified before parameters

**Comment by jhford** [comment]
Let's do vendoring, the chances of us needing updates to the CLI library are low I suspect.

**Comment by djmitche** [comment]
@petemoore is this still an issue?  It's  a one-liner that got bitrotten :)

**Comment by petemoore** [comment]
Closing for now as I'm not actively working on it.

**Pull request closed without merging**
